references:
  defaults: &defaults
    working_directory: ~/project
    docker:
      - image: circleci/node:8-browsers

  cache_key: &cache_key
    todo-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/

version: 2.1
orbs:
  percy: percy/agent@0.1.3
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          key: *cache_key
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          name: Save cache
          key: *cache_key
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .ssh
  test_1:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: echo 'export PERCY_TOKEN="$PROJECT1_TOKEN"' >> $BASH_ENV
      - run: echo 'export PERCY_PARALLEL_TOTAL=-1' >> $BASH_ENV
      - run:
          name: Run Percy Project 1
          command: yarn project:1

  test_2:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: echo 'export PERCY_TOKEN="$PROJECT2_TOKEN"' >> $BASH_ENV
      - run:
          name: Run Percy Project 2
          command: yarn project:2

workflows:
  version: 2.1
  default:
    jobs:
      - install
      - test_1:
          requires:
            - install
      - test_2:
          requires:
            - install
      - percy/finalize_all:
         requires:
           - test_1
